# Generated by Django 3.1 on 2020-08-07 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='eid',
            new_name='aid',
        ),
        migrations.AddField(
            model_name='session',
            name='cid',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
    ]
