# Generated by Django 3.1 on 2020-08-11 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200810_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='eid',
            new_name='cid',
        ),
    ]
